[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "gunicorn 'app:create_app()' --log-file -"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "on-failure"

[environments]
production.restartPolicyMaxRetries = 10 